# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

if [ -f ~/.dotfile/bash/private/profile ]; then
	. ~/.dotfile/bash/private/profile
fi
export PATH
export LANG=en_US.UTF-8
